version: "3.8"

services:
  db:
    image: postgres
    container_name: postgresdb
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: user
      POSTGRES_DB: db
# docker-compose up -d
